import { Column, CreateDateColumn, Entity, PrimaryGeneratedColumn } from 'typeorm';

export enum MoodTag {
  STRESS = 'stress',
  ANXIETY = 'anxiety',
  SADNESS = 'sadness',
  CALM = 'calm',
  TIRED = 'tired',
}

export enum MoodTopic {
  WORK = 'work',
  RELATIONSHIP = 'relationship',
  HEALTH = 'health',
  SLEEP = 'sleep',
  OTHER = 'other',
}

/**
 * The primary long-term memory table. Each user check-in is stored here as one row.
 * Sensitive: this is health data under GDPR Art. 9. Encryption at rest must be enabled through
 * the database configuration, not at the application level; see docs/GDPR_NOTES.md.
 */
@Entity('mood_entries')
export class MoodEntry {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column()
  userId!: string; // FK to the users table

  @Column({ type: 'enum', enum: MoodTag })
  moodTag!: MoodTag; // Claude Haiku output derived from the user's free text

  @Column({ type: 'int' })
  intensity!: number; // 1 to 5

  @Column({ type: 'enum', enum: MoodTopic, nullable: true })
  topic!: MoodTopic | null;

  @Column({ type: 'text', nullable: true })
  rawUserText!: string | null; // Original user text (optional; the user can delete it)

  @Column({ type: 'varchar', length: 300, nullable: true })
  aiSummary!: string | null; // Summary of no more than 50 words generated by Haiku

  @CreateDateColumn()
  createdAt!: Date;
}
